<a href="https://colab.research.google.com/github/KrungSalad/Google_Colab/blob/master/Assignment_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import r2_score,accuracy_score
# load dataset into Pandas DataFrame
df = pd.read_csv('cumulative.csv')
df.head()

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


rowid     kepid kepoi_name  ...         ra        dec koi_kepmag
0      1  10797460  K00752.01  ...  291.93423  48.141651     15.347
1      2  10797460  K00752.02  ...  291.93423  48.141651     15.347
2      3  10811496  K00753.01  ...  297.00482  48.134129     15.436
3      4  10848459  K00754.01  ...  285.53461  48.285210     15.597
4      5  10854555  K00755.01  ...  288.75488  48.226200     15.509

[5 rows x 50 columns]

Data Cleaning & Max-Min Normalize

In [2]:
df.dropna(axis = 1, how = 'all', inplace = True)
df.fillna(method='ffill' , inplace = True )
df.head()

rowid     kepid kepoi_name  ...         ra        dec koi_kepmag
0      1  10797460  K00752.01  ...  291.93423  48.141651     15.347
1      2  10797460  K00752.02  ...  291.93423  48.141651     15.347
2      3  10811496  K00753.01  ...  297.00482  48.134129     15.436
3      4  10848459  K00754.01  ...  285.53461  48.285210     15.597
4      5  10854555  K00755.01  ...  288.75488  48.226200     15.509

[5 rows x 48 columns]

In [3]:
q = df.drop('rowid', axis = 1)
q = q.drop('kepid', axis = 1)
q = q.drop('kepoi_name', axis = 1)
q = q.drop('koi_disposition', axis = 1)
q = q.drop('koi_pdisposition', axis = 1)
q = q.drop('koi_tce_delivname', axis = 1)
q = q.drop('kepler_name', axis = 1)
q.head()

koi_score  koi_fpflag_nt  koi_fpflag_ss  ...         ra        dec  koi_kepmag
0      1.000              0              0  ...  291.93423  48.141651      15.347
1      0.969              0              0  ...  291.93423  48.141651      15.347
2      0.000              0              1  ...  297.00482  48.134129      15.436
3      0.000              0              1  ...  285.53461  48.285210      15.597
4      1.000              0              0  ...  288.75488  48.226200      15.509

[5 rows x 41 columns]

In [4]:
from sklearn import preprocessing
x = q.values #returns a numpy array
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
X_normalized = pd.DataFrame(x_scaled, columns=q.columns)
X_normalized.head()

koi_score  koi_fpflag_nt  koi_fpflag_ss  ...        ra       dec  koi_kepmag
0      1.000            0.0            0.0  ...  0.552473  0.733837    0.642863
1      0.969            0.0            0.0  ...  0.552473  0.733837    0.642863
2      0.000            0.0            1.0  ...  0.784346  0.733360    0.649689
3      0.000            0.0            1.0  ...  0.259826  0.742947    0.662039
4      1.000            0.0            0.0  ...  0.407085  0.739203    0.655289

[5 rows x 41 columns]

PCA

In [5]:

variables = ['koi_fpflag_nt', 'koi_fpflag_ss',
       'koi_fpflag_co', 'koi_fpflag_ec', 'koi_period', 'koi_period_err1',
       'koi_period_err2', 'koi_time0bk', 'koi_time0bk_err1',
       'koi_time0bk_err2', 'koi_impact', 'koi_impact_err1', 'koi_impact_err2',
       'koi_duration', 'koi_duration_err1', 'koi_duration_err2', 'koi_depth',
       'koi_depth_err1', 'koi_depth_err2', 'koi_prad', 'koi_prad_err1',
       'koi_prad_err2', 'koi_teq', 'koi_insol', 'koi_insol_err1',
       'koi_insol_err2', 'koi_model_snr', 'koi_tce_plnt_num',
       'koi_steff', 'koi_steff_err1', 'koi_steff_err2',
       'koi_slogg', 'koi_slogg_err1', 'koi_slogg_err2', 'koi_srad',
       'koi_srad_err1', 'koi_srad_err2', 'ra', 'dec', 'koi_kepmag']
x = X_normalized.loc[:, variables].values
y = X_normalized.loc[:,['koi_score']].values

from sklearn.decomposition import PCA
pca = PCA(n_components=5)
principalComponents = pca.fit_transform(x)
principalDf = pd.DataFrame(data = principalComponents
             , columns = ['principal component 1', 'principal component 2', 'principal component 3', 'principal component 4'
             , 'principal component 5'])

finalDf = pd.concat([principalDf, X_normalized[['koi_score']]], axis = 1)
display(finalDf.head())
display(pca.explained_variance_ratio_)

principal component 1  ...  koi_score
0              -0.251969  ...      1.000
1              -0.258561  ...      0.969
2               0.413915  ...      0.000
3               0.374239  ...      0.000
4              -0.257432  ...      1.000

[5 rows x 6 columns]

array([0.29693626, 0.23759124, 0.15381005, 0.07627084, 0.0645923 ])

Plot

In [0]:
#sns.pairplot(df[['koi_period', 'koi_duration','koi_depth', 'koi_prad', 'koi_teq','koi_score']], kind='reg');

Data

In [0]:
from sklearn.model_selection import train_test_split
# PCA
X = finalDf[['principal component 1', 'principal component 2', 'principal component 3', 'principal component 4','principal component 5']]
y = finalDf['koi_score'].astype('int')

#X = df[['koi_period', 'koi_duration','koi_depth', 'koi_prad', 'koi_teq']]
#y = df['koi_score'].astype('int')

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 2)


In [8]:
display(X_train)
display(y_train)

principal component 1  ...  principal component 5
377               -0.234022  ...              -0.199480
2661              -0.281577  ...              -0.172607
9354              -0.219868  ...               0.085858
7494               0.418699  ...               0.222372
2207              -0.246394  ...              -0.391896
...                     ...  ...                    ...
1099               0.409830  ...               0.170981
2514              -0.228487  ...              -0.010945
6637              -0.219970  ...              -0.055900
2575              -0.260425  ...              -0.034055
7336              -0.225087  ...               0.112341

[7651 rows x 5 columns]

377     0
2661    0
9354    1
7494    0
2207    0
       ..
1099    0
2514    1
6637    0
2575    1
7336    0
Name: koi_score, Length: 7651, dtype: int64

In [9]:
display(X_test)
display(y_test)

principal component 1  ...  principal component 5
9276              -0.276191  ...               0.244468
6321              -0.576295  ...               0.282273
2006              -0.252550  ...               0.055001
2200              -0.242863  ...              -0.068587
5923              -0.199511  ...              -0.165722
...                     ...  ...                    ...
1939              -0.213463  ...              -0.102412
5305               0.422659  ...              -0.345065
8643               0.013580  ...               0.249540
2602              -0.282711  ...              -0.117506
48                -0.245761  ...               0.453227

[1913 rows x 5 columns]

9276    0
6321    0
2006    1
2200    0
5923    0
       ..
1939    1
5305    0
8643    0
2602    1
48      1
Name: koi_score, Length: 1913, dtype: int64

SVC

In [0]:
from sklearn.model_selection import cross_val_score
from sklearn.svm import SVC

classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
#accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
#accuracies.mean()

Accuracy ของ Data ที่นำไป Train Model SVC โดยใช้ K-Fold

In [11]:
from sklearn import model_selection 
from sklearn.model_selection import cross_val_score 

kfold = model_selection.KFold(n_splits=10, random_state=2)
clf = SVC(kernel = 'rbf', random_state = 0)
results = model_selection.cross_val_score (clf, X_train, y_train, cv=kfold, scoring= 'accuracy')
print("10-fold accuracy: %.3f" % (results.mean()))

/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:296: FutureWarning: Setting a random_state has no effect since shuffle is False. This will raise an error in 0.24. You should leave random_state to its default (None), or set shuffle=True.
  FutureWarning


10-fold accuracy: 0.802


ความถูกต้องของ Data ระหว่าง y_test , y_pred สำหรับ Model SVC

In [12]:
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.79      1.00      0.88      1514
           1       0.00      0.00      0.00       399

    accuracy                           0.79      1913
   macro avg       0.40      0.50      0.44      1913
weighted avg       0.63      0.79      0.70      1913

[[1514    0]
 [ 399    0]]


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


LogisticRegression

In [0]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
#accuracy = model.score(X_test, y_test)
#print(accuracy)

Accuracy ของ Data ที่นำไป Train Model LogisticRegression โดยใช้ K-Fold

In [14]:
from sklearn import model_selection 
from sklearn.model_selection import cross_val_score 

kfold = model_selection.KFold(n_splits=10, random_state=2)
clf = LogisticRegression()
results = model_selection.cross_val_score (clf, X_train, y_train, cv=kfold, scoring= 'accuracy')
print("10-fold accuracy: %.3f" % (results.mean()))

/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:296: FutureWarning: Setting a random_state has no effect since shuffle is False. This will raise an error in 0.24. You should leave random_state to its default (None), or set shuffle=True.
  FutureWarning


10-fold accuracy: 0.802


ความถูกต้องของ Data ระหว่าง y_test , y_pred สำหรับ Model LogisticRegression

In [15]:
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.79      1.00      0.88      1514
           1       1.00      0.01      0.01       399

    accuracy                           0.79      1913
   macro avg       0.90      0.50      0.45      1913
weighted avg       0.84      0.79      0.70      1913

[[1514    0]
 [ 397    2]]


In [16]:
display("y_test : ",y_test)
display("y_pred : ",y_pred)

'y_test : '

9276    0
6321    0
2006    1
2200    0
5923    0
       ..
1939    1
5305    0
8643    0
2602    1
48      1
Name: koi_score, Length: 1913, dtype: int64

'y_pred : '

array([0, 0, 0, ..., 0, 0, 0])

LinearDiscriminantAnalysis (LDA)

In [0]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)
Model=LinearDiscriminantAnalysis()
Model.fit(X_train,y_train)
y_pred=Model.predict(X_test)
#print('accuracy is ',accuracy_score(y_pred,y_test))

Accuracy ของ Data ที่นำไป Train Model LDA โดยใช้ K-Fold

In [18]:
from sklearn import model_selection 
from sklearn.model_selection import cross_val_score 

kfold = model_selection.KFold(n_splits=10, random_state=2)
clf = LinearDiscriminantAnalysis()
results = model_selection.cross_val_score (clf, X_train, y_train, cv=kfold, scoring= 'accuracy')
print("10-fold accuracy: %.3f" % (results.mean()))

10-fold accuracy: 0.802


/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:296: FutureWarning: Setting a random_state has no effect since shuffle is False. This will raise an error in 0.24. You should leave random_state to its default (None), or set shuffle=True.
  FutureWarning


ความถูกต้องของ Data ระหว่าง y_test , y_pred สำหรับ Model LDA

In [19]:
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.79      1.00      0.88      1514
           1       0.00      0.00      0.00       399

    accuracy                           0.79      1913
   macro avg       0.40      0.50      0.44      1913
weighted avg       0.63      0.79      0.70      1913

[[1514    0]
 [ 399    0]]


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
